#!/usr/bin/python

import os
import pandas
from scipy import stats

def load_transform_measure(filepath):
    if os.path.exists(filepath):
        df = pandas.DataFrame.from_csv(filepath)
        df[df < 0] = 0.0
        value, _ = stats.boxcox(df['value'])
        df.columns = ['raw' + id]
        df['scaled' + id] = value
        return df
    else:
        raise

data = pandas.DataFrame.from_csv('data/county_48ALHI.csv')
index = pandas.DataFrame.from_csv('data/list.csv')
for id in index.index:
    filepath = 'data/measures/%s.csv' % id
    df = load_transform_measure(filepath)
    data = data.join(df, how='left')

data.to_csv('data/all.csv')









